export const data = [
  {
    id: 45,
    disabled: false,
    name: 'default',
    order: 1,
    placeholder: '',
    label: 'Payment Location Code (PLC)',
    type: 'text',
    errors: [],
    value: '',
    element: 'input',
    validators: {
      required: true,
      maxLength: 10,
      minLength: 1,
    },
  },
  {
    id: 2322,
    name: 'payment',
    order: 2,
    placeholder: '',
    label: 'Payment Type',
    value: '',
    type: 'select',
    element: 'select',
    options: ['mastercard'],
    validators: {
      required: true,
    },
  },
  {
    id: 2322,
    disabled: false,
    name: 'paymentAmount',
    order: 2,
    placeholder: '',
    label: 'Payment Amount',
    type: 'text',
    errors: [],
    value: '',
    element: 'input',
    validators: {
      required: true,
      maxLength: 10,
      minLength: 1,
    },
  },
  {
    id: 2322,
    disabled: false,
    name: 'checkbox',
    order: 2,
    placeholder: '',
    label: 'Checkbox',
    type: 'checkbox',
    postion: 'vertical ',
    errors: [],
    value: '',
    element: 'checkbox',
    options: ['mastercard', 'debit'],
    validators: {
      required: true,
    },
  },
];
